SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE (F.CATEGORY, F.PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY F.PRICE DESC;